# Generated by Django 3.2.4 on 2021-06-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('course_number', models.IntegerField(default=0)),
                ('instructor', models.CharField(blank=True, default='', max_length=60)),
                ('duration', models.FloatField(default=0.0)),
            ],
        ),
    ]
